site_name: iLambda API Documentation
nav: 
  - Home: index.md
  - Token: token.md
  - Recommendation:
    - Overview: rec/overview.md
    - Data Integration:
      - 'ItemTable': rec/data_integration/item_table.md
      - 'ItemProperty': rec/data_integration/item_property.md
      - 'CategoryTable': rec/data_integration/category_table.md
      - 'NavCategoryTable': rec/data_integration/nav_category_table.md
      - 'NavCategoryMapping': rec/data_integration/nav_category_mapping.md
      - 'Event': rec/data_integration/event_table.md
      - 'Impression': rec/data_integration/impression_table.md
    - Service API:
      - 'Detail': rec/api/detail.md
      - 'Landing': rec/api/landing.md
      - 'Activity': rec/api/activity.md
  - Product Discovery:
    - 'Data Integration': product_discover/data_integration/ps_data_integration.md
    - 'Service API': product_discover/api/ps_api.md

theme:
  name: "material"
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
