site_name: iLambda API Documentation
nav: 
  - Home: index.md
  - Recommendation:
    - 'Data Integration': rec_data_integration.md
    - 'Service API': rec_api.md
  - Product Discovery:
    - 'Data Integration': ps_data_integration.md
    - 'Service API': ps_api.md

theme:
  name: "material"
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
