site_name: iLambda API Documentation
nav: 
  - Home: index.md
  - Data API: data_integration.md
  - Recommendation API: eda_service.md
theme:
  name: "material"
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
