site_name: iLambda API Documentation
nav: 
  - Home: index.md
  - Token: token.md
  - Recommendation:
    - Overview: rec_data_integration_item_table.md
    - Data Integration:
      - 'Overview': rec_data_integration_intro.md
      - 'ItemTable': rec_data_integration_item_table.md
    - Service API:
      - 'Overview': rec_api_overview.md
      - 'Landing': rec_api_landing.md
  - Product Discovery:
    - 'Data Integration': ps_data_integration.md
    - 'Service API': ps_api.md

theme:
  name: "material"
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
